// Mock seed data for the AptiCore / CSI Attendance prototype.
// Dates are generated relative to "today" so the demo always looks live.

function daysFromNow(n, hour = 10, minute = 0) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const SEED_USERS = [
  {
    id: 'u_admin',
    name: 'Aditi Sharma',
    grNumber: 'ADMIN001',
    password: 'admin123',
    rollNumber: '-',
    class: '-',
    division: '-',
    year: '-',
    department: 'CSI Core Committee',
    email: 'aditi.sharma@csidmce.ac.in',
    phone: '9876500001',
    role: 'superadmin',
    isApproved: true,
    createdAt: daysFromNow(-120),
  },
  {
    id: 'u_coord',
    name: 'Rahul Mehta',
    grNumber: 'COORD001',
    password: 'coord123',
    rollNumber: '-',
    class: '-',
    division: '-',
    year: 'TE',
    department: 'Computer Engineering',
    email: 'rahul.mehta@csidmce.ac.in',
    phone: '9876500002',
    role: 'coordinator',
    isApproved: true,
    createdAt: daysFromNow(-100),
  },
  {
    id: 'u_coord2',
    name: 'Priya Nair',
    grNumber: 'COORD002',
    password: 'coord123',
    rollNumber: '-',
    class: '-',
    division: '-',
    year: 'BE',
    department: 'Information Technology',
    email: 'priya.nair@csidmce.ac.in',
    phone: '9876500003',
    role: 'coordinator',
    isApproved: true,
    createdAt: daysFromNow(-95),
  },
  {
    id: 'u_vol1',
    name: 'Sneha Kulkarni',
    grNumber: 'VOL001',
    password: 'vol123',
    rollNumber: '21',
    class: 'TE-COMPS',
    division: 'A',
    year: 'TE',
    department: 'Computer Engineering',
    email: 'sneha.kulkarni@dmce.ac.in',
    phone: '9876500004',
    role: 'volunteer',
    isApproved: true,
    createdAt: daysFromNow(-80),
  },
  {
    id: 'u_vol2',
    name: 'Arjun Verma',
    grNumber: 'VOL002',
    password: 'vol123',
    rollNumber: '08',
    class: 'SE-IT',
    division: 'B',
    year: 'SE',
    department: 'Information Technology',
    email: 'arjun.verma@dmce.ac.in',
    phone: '9876500005',
    role: 'volunteer',
    isApproved: true,
    createdAt: daysFromNow(-80),
  },
  {
    id: 'u_vol3',
    name: 'Kabir Shah',
    grNumber: 'VOL003',
    password: 'vol123',
    rollNumber: '14',
    class: 'TE-EXTC',
    division: 'A',
    year: 'TE',
    department: 'Electronics & Telecom',
    email: 'kabir.shah@dmce.ac.in',
    phone: '9876500006',
    role: 'volunteer',
    isApproved: true,
    createdAt: daysFromNow(-70),
  },
  {
    id: 'u_s1',
    name: 'Isha Deshpande',
    grNumber: '22CO045',
    password: 'student123',
    rollNumber: '45',
    class: 'TE-COMPS',
    division: 'A',
    year: 'TE',
    department: 'Computer Engineering',
    email: 'isha.deshpande@dmce.ac.in',
    phone: '9876500010',
    role: 'student',
    isApproved: true,
    createdAt: daysFromNow(-60),
  },
  {
    id: 'u_s2',
    name: 'Yash Patil',
    grNumber: '22CO046',
    password: 'student123',
    rollNumber: '46',
    class: 'TE-COMPS',
    division: 'A',
    year: 'TE',
    department: 'Computer Engineering',
    email: 'yash.patil@dmce.ac.in',
    phone: '9876500011',
    role: 'student',
    isApproved: true,
    createdAt: daysFromNow(-59),
  },
  {
    id: 'u_s3',
    name: 'Ananya Rao',
    grNumber: '23IT012',
    password: 'student123',
    rollNumber: '12',
    class: 'SE-IT',
    division: 'B',
    year: 'SE',
    department: 'Information Technology',
    email: 'ananya.rao@dmce.ac.in',
    phone: '9876500012',
    role: 'student',
    isApproved: true,
    createdAt: daysFromNow(-55),
  },
  {
    id: 'u_s4',
    name: 'Devansh Joshi',
    grNumber: '21CO033',
    password: 'student123',
    rollNumber: '33',
    class: 'BE-COMPS',
    division: 'B',
    year: 'BE',
    department: 'Computer Engineering',
    email: 'devansh.joshi@dmce.ac.in',
    phone: '9876500013',
    role: 'student',
    isApproved: true,
    createdAt: daysFromNow(-50),
  },
  {
    id: 'u_s5',
    name: 'Meera Iyer',
    grNumber: '23EX021',
    password: 'student123',
    rollNumber: '21',
    class: 'SE-EXTC',
    division: 'A',
    year: 'SE',
    department: 'Electronics & Telecom',
    email: 'meera.iyer@dmce.ac.in',
    phone: '9876500014',
    role: 'student',
    isApproved: true,
    createdAt: daysFromNow(-45),
  },
  {
    id: 'u_s6',
    name: 'Rohan Kulkarni',
    grNumber: '22CO051',
    password: 'student123',
    rollNumber: '51',
    class: 'TE-COMPS',
    division: 'B',
    year: 'TE',
    department: 'Computer Engineering',
    email: 'rohan.kulkarni@dmce.ac.in',
    phone: '9876500015',
    role: 'student',
    isApproved: false,
    createdAt: daysFromNow(-2),
  },
  {
    id: 'u_s7',
    name: 'Tanvi Bhosale',
    grNumber: '23CO009',
    password: 'student123',
    rollNumber: '09',
    class: 'SE-COMPS',
    division: 'A',
    year: 'SE',
    department: 'Computer Engineering',
    email: 'tanvi.bhosale@dmce.ac.in',
    phone: '9876500016',
    role: 'student',
    isApproved: false,
    createdAt: daysFromNow(-1),
  },
  {
    id: 'u_s8',
    name: 'Aryan Kapoor',
    grNumber: '21IT018',
    password: 'student123',
    rollNumber: '18',
    class: 'BE-IT',
    division: 'A',
    year: 'BE',
    department: 'Information Technology',
    email: 'aryan.kapoor@dmce.ac.in',
    phone: '9876500017',
    role: 'student',
    isApproved: true,
    createdAt: daysFromNow(-40),
  },
];

export const SEED_EVENTS = [
  {
    id: 'e_hackfest',
    title: 'HackFest 2026 — 24hr Build Sprint',
    description:
      'A 24-hour hackathon for students to build working prototypes across open tracks: fintech, climate, and campus-life. Teams of up to 4, mentors on-site, and a live judging panel at the end.',
    type: 'contest',
    startDate: daysFromNow(9, 9, 0),
    endDate: daysFromNow(10, 11, 0),
    location: 'DMCE Innovation Lab, Block C',
    points: 60,
    registrationRequired: true,
    walkInAllowed: false,
    registrationDeadline: daysFromNow(8, 23, 59),
    createdBy: 'u_coord',
    status: 'upcoming',
    volunteers: ['u_vol1', 'u_vol2'],
    sessions: [],
  },
  {
    id: 'e_reactws',
    title: 'Modern React Workshop',
    description:
      'Hands-on workshop covering React 19, hooks, and component architecture. Bring your laptop — we will build a small app together from scratch.',
    type: 'workshop',
    startDate: daysFromNow(3, 14, 0),
    endDate: daysFromNow(3, 17, 0),
    location: 'Seminar Hall II',
    points: 20,
    registrationRequired: true,
    walkInAllowed: true,
    registrationDeadline: daysFromNow(3, 13, 0),
    createdBy: 'u_coord',
    status: 'upcoming',
    volunteers: ['u_vol2'],
    sessions: [],
  },
  {
    id: 'e_aitalk',
    title: 'Guest Talk: Applied AI in Industry',
    description:
      'An industry seminar on how applied machine learning teams ship products at scale, followed by an open Q&A session with the speaker.',
    type: 'seminar',
    startDate: daysFromNow(0, 15, 0),
    endDate: daysFromNow(0, 17, 0),
    location: 'Main Auditorium',
    points: 10,
    registrationRequired: true,
    walkInAllowed: true,
    registrationDeadline: daysFromNow(0, 14, 30),
    createdBy: 'u_coord2',
    status: 'ongoing',
    volunteers: ['u_vol1', 'u_vol3'],
    sessions: [],
  },
  {
    id: 'e_designsprint',
    title: 'Product Design Sprint',
    description:
      'A three-day design sprint covering research, ideation, prototyping, and testing. Each day is tracked as an independent session.',
    type: 'multiday',
    startDate: daysFromNow(-1, 9, 0),
    endDate: daysFromNow(1, 18, 0),
    location: 'Design Studio, Block A',
    points: 15,
    registrationRequired: true,
    walkInAllowed: false,
    registrationDeadline: daysFromNow(-2, 23, 59),
    createdBy: 'u_coord',
    status: 'ongoing',
    volunteers: ['u_vol2', 'u_vol3'],
    sessions: [
      { id: 'sess_1', label: 'Day 1 — Research & Ideation', date: daysFromNow(-1, 9, 0) },
      { id: 'sess_2', label: 'Day 2 — Prototyping', date: daysFromNow(0, 9, 0) },
      { id: 'sess_3', label: 'Day 3 — Testing & Pitch', date: daysFromNow(1, 9, 0) },
    ],
  },
  {
    id: 'e_gitworkshop',
    title: 'Git & GitHub Essentials',
    description:
      'A beginner-friendly workshop on version control fundamentals: branches, merges, pull requests, and collaborative workflows.',
    type: 'workshop',
    startDate: daysFromNow(-14, 11, 0),
    endDate: daysFromNow(-14, 13, 0),
    location: 'Computer Lab 4',
    points: 15,
    registrationRequired: true,
    walkInAllowed: true,
    registrationDeadline: daysFromNow(-15, 23, 59),
    createdBy: 'u_coord2',
    status: 'closed',
    volunteers: ['u_vol1'],
    sessions: [],
  },
  {
    id: 'e_debrief',
    title: 'CSI Q2 Debriefing Session',
    description:
      'Quarterly debriefing session for all CSI members covering completed events, budgets, and plans for the next quarter.',
    type: 'debriefing',
    startDate: daysFromNow(-7, 16, 0),
    endDate: daysFromNow(-7, 18, 0),
    location: 'Committee Room',
    points: 5,
    registrationRequired: false,
    walkInAllowed: true,
    registrationDeadline: daysFromNow(-7, 15, 30),
    createdBy: 'u_admin',
    status: 'closed',
    volunteers: [],
    sessions: [],
  },
  {
    id: 'e_dsacontest',
    title: 'DSA Speed Coding Contest',
    description:
      'A timed competitive programming contest covering arrays, trees, graphs, and dynamic programming. Top 3 teams win CSI merchandise.',
    type: 'contest',
    startDate: daysFromNow(-30, 10, 0),
    endDate: daysFromNow(-30, 13, 0),
    location: 'Computer Lab 2',
    points: 25,
    registrationRequired: true,
    walkInAllowed: false,
    registrationDeadline: daysFromNow(-31, 23, 59),
    createdBy: 'u_coord',
    status: 'closed',
    volunteers: ['u_vol2', 'u_vol1'],
    sessions: [],
  },
  {
    id: 'e_cloudsem',
    title: 'Cloud Native Fundamentals',
    description:
      'An introductory seminar on containers, orchestration, and cloud-native design patterns for modern applications.',
    type: 'seminar',
    startDate: daysFromNow(18, 15, 0),
    endDate: daysFromNow(18, 17, 30),
    location: 'Seminar Hall I',
    points: 10,
    registrationRequired: true,
    walkInAllowed: true,
    registrationDeadline: daysFromNow(18, 14, 0),
    createdBy: 'u_coord2',
    status: 'upcoming',
    volunteers: [],
    sessions: [],
  },
];

// Registrations: { id, student, event, registeredAt, qrToken, isWalkIn }
// Attendance: { id, registration, student, event, session, scannedBy, scannedAt, pointsAwarded, offlineSyncStatus }
// Populated by lib/store.js seed step (needs token generation helper), kept here as plain relation lists.

export const SEED_REGISTRATIONS = [
  { student: 'u_s1', event: 'e_hackfest', daysAgo: 4 },
  { student: 'u_s2', event: 'e_hackfest', daysAgo: 3 },
  { student: 'u_s3', event: 'e_hackfest', daysAgo: 2 },
  { student: 'u_s1', event: 'e_reactws', daysAgo: 5 },
  { student: 'u_s4', event: 'e_reactws', daysAgo: 4 },
  { student: 'u_s5', event: 'e_reactws', daysAgo: 1 },
  { student: 'u_s1', event: 'e_aitalk', daysAgo: 6 },
  { student: 'u_s2', event: 'e_aitalk', daysAgo: 5 },
  { student: 'u_s3', event: 'e_aitalk', daysAgo: 5 },
  { student: 'u_s4', event: 'e_aitalk', daysAgo: 3 },
  { student: 'u_s8', event: 'e_aitalk', daysAgo: 2 },
  { student: 'u_s1', event: 'e_designsprint', daysAgo: 10 },
  { student: 'u_s3', event: 'e_designsprint', daysAgo: 9 },
  { student: 'u_s5', event: 'e_designsprint', daysAgo: 8 },
  { student: 'u_s1', event: 'e_gitworkshop', daysAgo: 20 },
  { student: 'u_s2', event: 'e_gitworkshop', daysAgo: 19 },
  { student: 'u_s4', event: 'e_gitworkshop', daysAgo: 18 },
  { student: 'u_s8', event: 'e_gitworkshop', daysAgo: 17, isWalkIn: true },
  { student: 'u_s1', event: 'e_dsacontest', daysAgo: 35 },
  { student: 'u_s2', event: 'e_dsacontest', daysAgo: 34 },
  { student: 'u_s3', event: 'e_dsacontest', daysAgo: 33 },
  { student: 'u_s4', event: 'e_dsacontest', daysAgo: 33 },
  { student: 'u_s5', event: 'e_dsacontest', daysAgo: 32 },
];

// Which registrations already have confirmed attendance (by student+event key), for closed/past events.
export const SEED_ATTENDANCE_KEYS = [
  'u_s1|e_gitworkshop',
  'u_s2|e_gitworkshop',
  'u_s4|e_gitworkshop',
  'u_s8|e_gitworkshop',
  'u_s1|e_dsacontest',
  'u_s2|e_dsacontest',
  'u_s3|e_dsacontest',
  'u_s1|e_designsprint|sess_1',
  'u_s3|e_designsprint|sess_1',
  'u_s1|e_aitalk',
];
